22 sprint (Плейлисты)
NSPROJ/MyPlaylistMaker pull request #16
Opened 2024-11-27 08:21 UTC by NSPROJ

2024-11-27 13:34 UTC, DmitrijEgorow requested changes

2024-11-27 13:34 UTC, DmitrijEgorow commented on app/src/main/java/com/example/myplaylistmaker/media/domain/Playlist.kt
> +    var trackId:MutableList<Int>,
Лучше оставить в [data class неизменяемые свойства](https://www.reddit.com/r/Kotlin/comments/qibnqc/comment/hijhupt/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button)

2024-11-27 13:34 UTC, DmitrijEgorow commented on app/src/main/java/com/example/myplaylistmaker/media/ui/adapters/PlaylistTracksAdapter.kt
> +    RecyclerView.Adapter<PlaylistTracksViewHolder>() {
Code → Reformat Code

2024-11-27 13:34 UTC, DmitrijEgorow commented on app/src/main/java/com/example/myplaylistmaker/media/ui/adapters/PlaylistTracksViewHolder.kt
> +    private fun getEnding(number: Int): String {
11 треков, но остаток 1

2024-11-27 13:34 UTC, DmitrijEgorow commented on app/src/main/java/com/example/myplaylistmaker/media/ui/adapters/PlaylistViewHolder.kt
> +    private fun getEnding(number: Int): String {
Стоит избавиться от дублирования кода

2024-11-27 13:34 UTC, DmitrijEgorow commented on app/src/main/java/com/example/myplaylistmaker/media/ui/fragments/NewPlayFragment.kt
> +                "Плейлист ${playlistName.text} успешно создан!",
Лучше string-res

2024-11-27 13:34 UTC, DmitrijEgorow commented on app/src/main/java/com/example/myplaylistmaker/media/ui/fragments/NewPlayFragment.kt
> +        val filePath = File(requireContext().getExternalFilesDir(Environment.DIRECTORY_PICTURES), "playlist_images")
Работа с файлами в presentation слое

2024-11-27 13:34 UTC, DmitrijEgorow commented on app/src/main/java/com/example/myplaylistmaker/media/ui/fragments/PlaylistsFragment.kt
> +        textPlaceholder = binding.mediaPlaceholderTv
```suggestion
        with(binding) {
                PlaylistsRecyclerView.layoutManager = GridLayoutManager(requireContext(), 2)
               PlaylistsRecyclerView.adapter = playlistAdapter
               ...
        }        
```

2024-11-27 13:34 UTC, DmitrijEgorow commented on app/src/main/java/com/example/myplaylistmaker/media/ui/fragments/PlaylistsFragment.kt
> +                binding.PlaylistsRecyclerView.visibility = View.VISIBLE
Почему `PlaylistsRecyclerView` с большой буквы?

2024-11-27 13:34 UTC, DmitrijEgorow commented on app/src/main/res/layout/activity_player.xml
> +                android:id="@+id/imageView"
Не самый удачный идентификатор

2024-11-27 13:34 UTC, DmitrijEgorow commented on app/src/main/res/layout/bottom_sheet_item.xml
> +                android:id="@+id/track_count"
Разные стили именования идентификатора: где-то через _, где-то с camelCase

2024-11-27 14:26 UTC, DmitrijEgorow commented
- [ ] 	Фиолетовый цвет не входит в цветовую палитру приложения


![Screenshot_20241127_170421](https://github.com/user-attachments/assets/9f2a7de2-6e01-4e1e-af84-cec813ebeac5)

2024-11-27 14:27 UTC, DmitrijEgorow commented
- [ ] Текстовые поля ввода не соответствуют дизайн-макету: цвет курсора, обводка в фокусе
- [ ] Ввести в эти поля и нажать на кнопку на маленьких диагоналях не представляется возможным
![Screenshot_20241127_170454](https://github.com/user-attachments/assets/c849e324-35bc-402c-997c-16597db1676d)

2024-11-27 16:17 UTC, NSPROJ commented on app/src/main/java/com/example/myplaylistmaker/media/ui/fragments/NewPlayFragment.kt
> +        val filePath = File(requireContext().getExternalFilesDir(Environment.DIRECTORY_PICTURES), "playlist_images")
Доброго времени суток. Не знал , что её надо убирать , теперь убрал. 
А работа с новой базой данных для треков реализована в playlist классах

2024-11-28 15:50 UTC, DmitrijEgorow commented
> * [ ]  Текстовые поля ввода не соответствуют дизайн-макету: цвет курсора, обводка в фокусе
> 
>     * [ ]  Ввести в эти поля и нажать на кнопку на маленьких диагоналях не представляется возможным
>       ![Screenshot_20241127_170454](https://private-user-images.githubusercontent.com/36837067/390448264-c849e324-35bc-402c-997c-16597db1676d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4MDc5MTYsIm5iZiI6MTczMjgwNzYxNiwicGF0aCI6Ii8zNjgzNzA2Ny8zOTA0NDgyNjQtYzg0OWUzMjQtMzViYy00MDJjLTk5N2MtMTY1OTdkYjE2NzZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI4VDE1MjY1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlZWVhZjQzNzczOWI2NTA2MzhlMjk3YTI5ZDNlZWI0NzIyNWMwZWEwMzEwM2JhYWE0NTYzYzAyOWU4YWJmZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.qKcWrImXo0BnTxtpHf9e4CsisDPOhubdih4eXu60G2M)
> 
> 
> ![Screenshot_20241127_170838](https://private-user-images.githubusercontent.com/36837067/390448387-7139ef48-b477-465e-bdef-d2695a5a927c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4MDc5MTYsIm5iZiI6MTczMjgwNzYxNiwicGF0aCI6Ii8zNjgzNzA2Ny8zOTA0NDgzODctNzEzOWVmNDgtYjQ3Ny00NjVlLWJkZWYtZDI2OTVhNWE5MjdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI4VDE1MjY1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcyZGI0OGI1MTUzZDFkNjJiYzE1NTc3MWVmYTM4YzkzMTk2MzU5ZjUxNWJkNTdlNzVhZjcwN2EyYjc0NjVkNjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.nSguDF2RFsyc_XJCfhLuDEMHEcJb7ss8G28AnpheUFM)

Актуально

2024-11-28 16:51 UTC, DmitrijEgorow commented
- [ ] 	Последние две карточки плейлистов не прокручиваются до конца

https://github.com/user-attachments/assets/9cef1465-78ac-4ffe-a4c5-d7164064b240

2024-11-28 16:51 UTC, DmitrijEgorow commented
- [ ] Когда на экране видна клавиатура, панель навигации должна скрываться за ней.



https://github.com/user-attachments/assets/a9ad7054-1ff6-418f-82ff-0e47cd7aaa14

2024-11-28 16:52 UTC, DmitrijEgorow commented
- [ ] 	Треки, добавляемые в плейлист, должны сохраняться в отдельную таблицу базы данных
<img width="1504" alt="Screenshot 2024-11-28 at 19 46 25" src="https://github.com/user-attachments/assets/ffc29ee3-2269-4abf-8b8b-99955a1f1b77">

2024-12-02 23:44 UTC, DmitrijEgorow commented
> * [ ]  Текстовые поля ввода не соответствуют дизайн-макету: цвет курсора, обводка в фокусе
> 
>     * [ ]  Ввести в эти поля и нажать на кнопку на маленьких диагоналях не представляется возможным
>       ![Screenshot_20241127_170454](https://private-user-images.githubusercontent.com/36837067/390448264-c849e324-35bc-402c-997c-16597db1676d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxODI1MTksIm5iZiI6MTczMzE4MjIxOSwicGF0aCI6Ii8zNjgzNzA2Ny8zOTA0NDgyNjQtYzg0OWUzMjQtMzViYy00MDJjLTk5N2MtMTY1OTdkYjE2NzZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAyVDIzMzAxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2Yzc5Nzg3NGFlOGJiZjMzYjk5NzRiZGUzOGRhMzA3ZDJjZDczMmJiODljODhjMjdjMTM0MGYxMDE4MWMzMWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.3CypSBNzz7axufcoDeP83pZVlrbAZOe0Nn_JOnUdaa4)
> 
> 
> ![Screenshot_20241127_170838](https://private-user-images.githubusercontent.com/36837067/390448387-7139ef48-b477-465e-bdef-d2695a5a927c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxODI1MTksIm5iZiI6MTczMzE4MjIxOSwicGF0aCI6Ii8zNjgzNzA2Ny8zOTA0NDgzODctNzEzOWVmNDgtYjQ3Ny00NjVlLWJkZWYtZDI2OTVhNWE5MjdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAyVDIzMzAxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkMmYyNDkwNzcxMjQxOTczMzg2N2U3Zjc4YjY2YTYwZTVjMGM4NGY1NjBkOGFkM2M4YTZkODI1OTU4ZjI0Y2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.xeubZ48gNDNc9eRwgw1fObnXmq8wP-P5GmURYv41Szc)

Актуально про цвет курсора

2024-12-02 23:44 UTC, DmitrijEgorow commented
> * [ ]  	Последние две карточки плейлистов не прокручиваются до конца
> 
> 
> Screen_recording_20241128_194115.mp4

Актуально

2024-12-09 20:03 UTC, merged